project:
  type: website
  output-dir: docs

website:
  title: "Natalia Cabrera-Morales"

  navbar:
    left:
      - text: PhD
        href: phd.qmd
      - text: Research
        href: research.qmd
      - text: Teaching
        href: teaching.qmd
      - text: About me
        href: me.qmd
    right:
      - icon: github
        href: https://github.com/NcabreraM
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/ncabrera-morales/
        aria-label: LinkedIn
      - icon: envelope
        href: mailto:nc606@cam.ac.uk
        aria-label: Email

format:
  html:
    theme: 
      - cosmo
      - styles.scss

editor: visual

