---
title: ""
---

Viento trágico de alas negras

azota al guásimo y al yarumo.

Gimiendo van por la quebrada

Viento acre olor a humo.

Solloza angustia amarga el obscuro platanal

y danza loca la llama en el rubio maizal.

Hay hombres persiguiendo,

hombres que atacan y hombres huyendo.

Arde el ranchito blanco

allá en la verde loma.

Sombras sigilosas por el barranco

Después…. silencio… y cenizas.

Y mil cuervos hambrientos

en picada bajo la nube plomiza

En el regazo de la tierra

Cuajan bermejas flores

Y en manojos apretados

nieva la cal, sus faldas de colores.

Turbias las aguas del río

Aguas con sabor a sangre

Envolviendo cuerpos fríos.

Corazones en su canto silenciados,

Que ayer fueron primavera;

De anhelos y promesa iluminados,

Como el cielo de la luna plena.

Pobre hombre amasado en tinieblas.

¿No sientes que tu alma la oprimen resinas muy negras?

En tus labios se helará la sonrisa

y en tus manos tejidas de besos

ya no podrán anidar las caricias.

¡Oh hermano!...

Tal vez, no tienes la culpa…

Se olvidaron los siglos del pobre Caín,

y Caín sigue errando por la tierra madura

y empuña tu mano, por ver si él puede morir.

Colombia sangra en silencio,

Ella misma clávase en el madero.

Se ha olvidado de Jesús el Nazareno

y de su voz clamorosa en el desierto.

Esta patria enlutada no es la mía,

Pero es pétalo fulgente de América Latina.

Pero su dolor callado,

y su profunda herida,

Están filtrando

por mi alma estremecida.

*Elcira Caamaño Gutiérrez*

------------------------------------------------------------------------
